# Generated by Django 4.0.6 on 2022-07-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='shoe.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
