# Generated by Django 4.0.6 on 2022-07-26 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
